/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cgpagenerator;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author waugh
 */
public class StudyProblem extends javax.swing.JFrame {

    /**
     * Creates new form StudyProblem
     */
    String str1, dept, sem;
    int dep, semester,choice;
    String s1[] = new String[]{"CSE", "CE", "EEE", "ME", "TE", "IPE", "ARCH"};
    String s2[] = new String[]{"1st Year 1st Semester", "1st Year 2nd Semester", "2nd Year 1st Semester", "2nd Year 2nd Semester", "3rd Year 1st Semester", "3rd Year 2nd Semester", "4th Year 1st Semester", "4th Year 2nd Semester", "5th Year 1st Semester", "5th Year 2nd Semester"};
    Connection con = null;

    public StudyProblem() {
        try {
            initComponents();
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/Student", "WAUGHFA", "WAUGHFA");
        } catch (SQLException ex) {
            // Logger.getLogger(EnterPassword.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Connection Error", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public StudyProblem(String ID, String Department, String Semester) {
        try {
            initComponents();
            str1 = ID;
            dept = Department;
            sem = Semester;
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/Student", "WAUGHFA", "WAUGHFA");
        } catch (SQLException ex) {
            // Logger.getLogger(EnterPassword.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Connection Error", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public void selectChoice(){
        int a = Integer.parseInt(dept);
        int b = Integer.parseInt(sem);
        choice = (a*10)+b;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 250));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setText("The Subject You have Problem in:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 147, 239, 34));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 255));
        jLabel2.setText("The Topic You have Problem in:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 258, 239, 34));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 204, 255));
        jLabel3.setText("Description Of Your Problem:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 372, 239, 34));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 149, 488, 34));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 260, 488, 34));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 374, 488, 34));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 486, 107, 35));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 566, 84, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picbg/Bg2.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dep = Integer.parseInt(dept);
        semester = Integer.parseInt(sem);
        String sub = jTextField1.getText();
        String topic = jTextField2.getText();
        String desc = jTextField3.getText();
        int row = -1;
        String sql = "INSERT INTO PROBLEM (ID,DEPARTMENT,SEMESTER,SUBJECT,TOPIC,DESCRIPTION) VALUES (?,?,?,?,?,?)";
        try {
            System.out.println("");

            PreparedStatement ps = con.prepareCall(sql);
            ps.setString(1, str1);
            ps.setString(2, s1[dep-1]);
            ps.setString(3, s2[semester-1]);
            ps.setString(4, sub);
            ps.setString(5, topic);
            ps.setString(6, desc);
            row = ps.executeUpdate();
            //JOptionPane.showMessageDialog(null, "Data insertion Successful" + row, "info", JOptionPane.INFORMATION_MESSAGE);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Insertion Error. Row Affected" + row, JOptionPane.INFORMATION_MESSAGE);
        }
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        selectChoice(); 
        switch (choice) {
            case 11:
                this.setVisible(false);
                CseoneoneHub obj1 = new CseoneoneHub(str1);
                obj1.setVisible(true);
                break;
            case 12:
                this.setVisible(false);
                CseonetwoHub obj2 = new CseonetwoHub(str1);
                obj2.setVisible(true);
                break;
            case 13:
                this.setVisible(false);
                CsetwooneHub obj3 = new CsetwooneHub(str1);
                obj3.setVisible(true);
                break;
            case 14:
                this.setVisible(false);
                CsetwotwoHub obj4 = new CsetwotwoHub(str1);
                obj4.setVisible(true);
                break;
            case 15:
                this.setVisible(false);
                CsethreeoneHub obj5 = new CsethreeoneHub(str1);
                obj5.setVisible(true);
                break;
            case 16:
                this.setVisible(false);
                CsethreetwoHub obj6 = new CsethreetwoHub(str1);
                obj6.setVisible(true);
                break;
            case 17:
                this.setVisible(false);
                CsefouroneHub obj7 = new CsefouroneHub(str1);
                obj7.setVisible(true);
                break;
            case 18:
                this.setVisible(false);
                CsefourtwoHub obj8 = new CsefourtwoHub(str1);
                obj8.setVisible(true);
                break;

            case 21:
                this.setVisible(false);
                CeoneoneHub obj9 = new CeoneoneHub(str1);
                obj9.setVisible(true);
                break;
            case 22:
                this.setVisible(false);
                CeonetwoHub obj10 = new CeonetwoHub(str1);
                obj10.setVisible(true);
                break;
            case 23:
                this.setVisible(false);
                CetwooneHub obj11 = new CetwooneHub(str1);
                obj11.setVisible(true);
                break;
            case 24:
                this.setVisible(false);
                CetwotwoHub obj12 = new CetwotwoHub(str1);
                obj12.setVisible(true);
                break;
            case 25:
                this.setVisible(false);
                CethreeoneHub obj13 = new CethreeoneHub(str1);
                obj13.setVisible(true);
                break;
            case 26:
                this.setVisible(false);
                CethreetwoHub obj14 = new CethreetwoHub(str1);
                obj14.setVisible(true);
                break;
            case 27:
                this.setVisible(false);
                CefouroneHub obj15 = new CefouroneHub(str1);
                obj15.setVisible(true);
                break;
            case 28:
                this.setVisible(false);
                CefourtwoHub obj16 = new CefourtwoHub(str1);
                obj16.setVisible(true);
                break;
            case 31:
                this.setVisible(false);
                eeeoneoneHub obj17 = new eeeoneoneHub(str1);
                obj17.setVisible(true);
                break;
            case 32:
                this.setVisible(false);
                eeeonetwoHub obj18 = new eeeonetwoHub(str1);
                obj18.setVisible(true);
                break;
            case 33:
                this.setVisible(false);
                eeetwooneHub obj19 = new eeetwooneHub(str1);
                obj19.setVisible(true);
                break;
            case 34:
                this.setVisible(false);
                eeetwotwoHub obj20 = new eeetwotwoHub(str1);
                obj20.setVisible(true);
                break;
            case 35:
                this.setVisible(false);
                eeethreeoneHub obj21 = new eeethreeoneHub(str1);
                obj21.setVisible(true);
                break;
            case 36:
                this.setVisible(false);
                eeethreetwoHub obj22 = new eeethreetwoHub(str1);
                obj22.setVisible(true);
                break;
            case 37:
                this.setVisible(false);
                eeefouroneHub obj23 = new eeefouroneHub(str1);
                obj23.setVisible(true);
                break;
            case 38:
                this.setVisible(false);
                eeefourtwoHub obj24 = new eeefourtwoHub(str1);
                obj24.setVisible(true);
                break;
            case 41:
                this.setVisible(false);
                MeoneoneHub obj25 = new MeoneoneHub(str1);
                obj25.setVisible(true);
                break;
            case 42:
                this.setVisible(false);
                MeonetwoHub obj26 = new MeonetwoHub(str1);
                obj26.setVisible(true);
                break;
            case 43:
                this.setVisible(false);
                MetwooneHub obj27 = new MetwooneHub(str1);
                obj27.setVisible(true);
                break;
            case 44:
                this.setVisible(false);
                MetwotwoHub obj28 = new MetwotwoHub(str1);
                obj28.setVisible(true);
                break;
            case 45:
                this.setVisible(false);
                MethreeoneHub obj29 = new MethreeoneHub(str1);
                obj29.setVisible(true);
                break;
            case 46:
                this.setVisible(false);
                MethreetwoHub obj30 = new MethreetwoHub(str1);
                obj30.setVisible(true);
                break;
            case 47:
                this.setVisible(false);
                MefouroneHub obj31 = new MefouroneHub(str1);
                obj31.setVisible(true);
                break;
            case 48:
                this.setVisible(false);
                MefourtwoHub obj32 = new MefourtwoHub(str1);
                obj32.setVisible(true);
                break;
            case 51:
                this.setVisible(false);
                TeoneoneHub obj33 = new TeoneoneHub(str1);
                obj33.setVisible(true);
                break;
            case 52:
                this.setVisible(false);
                TeonetwoHub obj34 = new TeonetwoHub(str1);
                obj34.setVisible(true);
                break;
            case 53:
                this.setVisible(false);
                TetwooneHub obj35 = new TetwooneHub(str1);
                obj35.setVisible(true);
                break;
            case 54:
                this.setVisible(false);
                TetwotwoHub obj36 = new TetwotwoHub(str1);
                obj36.setVisible(true);
                break;
            case 55:
                this.setVisible(false);
                TethreeoneHub obj37 = new TethreeoneHub(str1);
                obj37.setVisible(true);
                break;
            case 56:
                this.setVisible(false);
                TethreetwoHub obj38 = new TethreetwoHub(str1);
                obj38.setVisible(true);
                break;
            case 57:
                this.setVisible(false);
                TefouroneHub obj39 = new TefouroneHub(str1);
                obj39.setVisible(true);
                break;
            case 58:
                this.setVisible(false);
                TefourtwoHub obj40 = new TefourtwoHub(str1);
                obj40.setVisible(true);
                break;
            case 61:
                this.setVisible(false);
                IpeoneoneHub obj41 = new IpeoneoneHub(str1);
                obj41.setVisible(true);
                break;
            case 62:
                this.setVisible(false);
                IpeonetwoHub obj42 = new IpeonetwoHub(str1);
                obj42.setVisible(true);
                break;
            case 63:
                this.setVisible(false);
                IpetwooneHub obj43 = new IpetwooneHub(str1);
                obj43.setVisible(true);
                break;
            case 64:
                this.setVisible(false);
                IpetwotwoHub obj44 = new IpetwotwoHub(str1);
                obj44.setVisible(true);
                break;
            case 65:
                this.setVisible(false);
                IpethreeoneHub obj45 = new IpethreeoneHub(str1);
                obj45.setVisible(true);
                break;
            case 66:
                this.setVisible(false);
                IpethreetwoHub obj46 = new IpethreetwoHub(str1);
                obj46.setVisible(true);
                break;
            case 67:
                this.setVisible(false);
                IpefouroneHub obj47 = new IpefouroneHub(str1);
                obj47.setVisible(true);
                break;
            case 68:
                this.setVisible(false);
                IpefourtwoHub obj48 = new IpefourtwoHub(str1);
                obj48.setVisible(true);
                break;
            case 71:
                this.setVisible(false);
                ArchioneoneHub obj51 = new ArchioneoneHub(str1);
                obj51.setVisible(true);
                break;
            case 72:
                this.setVisible(false);
                ArchionetwoHub obj52 = new ArchionetwoHub(str1);
                obj52.setVisible(true);
                break;
            case 73:
                this.setVisible(false);
                ArchitwooneHub obj53 = new ArchitwooneHub(str1);
                obj53.setVisible(true);
                break;
            case 74:
                this.setVisible(false);
                ArchitwotwoHub obj54 = new ArchitwotwoHub(str1);
                obj54.setVisible(true);
                break;
            case 75:
                this.setVisible(false);
                ArchithreeoneHub obj55 = new ArchithreeoneHub(str1);
                obj55.setVisible(true);
                break;
            case 76:
                this.setVisible(false);
                ArchithreetwoHub obj56 = new ArchithreetwoHub(str1);
                obj56.setVisible(true);
                break;
            case 77:
                this.setVisible(false);
                ArchifouroneHub obj57 = new ArchifouroneHub(str1);
                obj57.setVisible(true);
                break;
            case 78:
                this.setVisible(false);
                ArchifourtwoHub obj58 = new ArchifourtwoHub(str1);
                obj58.setVisible(true);
                break;
            case 79:
                this.setVisible(false);
                ArchifiveoneHub obj59 = new ArchifiveoneHub(str1);
                obj59.setVisible(true);
                break;
            default:
                this.setVisible(false);
                ArchifivetwoHub obj60 = new ArchifivetwoHub(str1);
                obj60.setVisible(true);
                break;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudyProblem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudyProblem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudyProblem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudyProblem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudyProblem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
